### ISSUE TITLE
issue adding widgets to CardStack

### ISSUE THREAD

**Issue by Lightning-blade** [Guhan-SenSam/CardStack#2]
hi

nice widget!!! Thank you.

could you give an example on how to add a widget to the cardstack?

when using current_card.add_widget() an error is returned saying AttributeError: 'NoneType' object has no attribute 'add_widget'

So please give me an example on how you would add a widget to cardstack

**Comment by Guhan-SenSam** [comment]
Hi. Actually I had completely forgotten about this widget. I have updated the code just now. There is also an example file to help you get started. If you still have any problem just post a comment here ,ill take a look into it

**Comment by Lightning-blade** [comment]
thanks, the change() method has to be called first before it can show its widgets. However i seem to be having a problem with adding custom widgets to the cardstack. here is the code below:
the main.py file:

`from kivymd.app import MDApp`
`from kivy.lang import Builder`
`from kivy.core.window import Window`
`from kivy.uix.screenmanager import ScreenManager`
`from akivymd.uix.cardstack import CardStack`
`from kivymd.uix.card import MDCardSwipe`

`Window.size = (250, 500)`


```
class theStack(CardStack):
   pass


class ToDoCard(MDCardSwipe):
    pass
```



```
class MainApp(MDApp):
    def build(self):
        global sm
        self.ts = theStack()
        sm = ScreenManager()
        sm.add_widget(Builder.load_file("main.kv"))
        return sm


    def on_start(self):
        self.ts.change()
        self.ts.current_card.add_widget(ToDoCard())


if __name__ == '__main__':
    MainApp().run()`

```
the main.kv file:

`#:import get_color_from_hex kivy.utils.get_color_from_hex`



```
<theStack>
    first_color: get_color_from_hex("#231b2d")
    second_color: get_color_from_hex("#2ab9b9")
    third_color: get_color_from_hex("#008080")
    card_in_direction: 'bottom'
    card_out_direction: 'left'
    elevation: 15
    pos_hint: {'center_x': .54, 'center_y': .42}
    size: ("530dp", "800dp")

<ToDoCard>
    padding: "8dp"
    id: tdcard
    anchor: "left"
    type_swipe: "hand"
    ripple_behavior: False
    size_hint_y: None
    height: thetodo.height

    MDCardSwipeLayerBox:
        size_hint_y: None
        height: thetodo.height
        size_hint_x: .97

    MDCardSwipeFrontBox:
        id: frontbox
        md_bg_color: get_color_from_hex("#008080")
        size_hint_y: None
        size_hint_x: .97
        height: thetodo.height
        radius: [60, 60, 60, 60]
        MDSeparator:
            id: bar
            orientation: "vertical"
            color: get_color_from_hex("#ffffff")
            size_hint_x: None
            size_hint_y: None
            height: thetodo.height
            width: "3dp"
        TwoLineListItem:
            id: thetodo
            text: "hello"
            bg_color: get_color_from_hex("#008080")
            secondary_text: "world"
            _no_ripple_effect: True
            pos_hint: {'x': .2, 'top': 1}
            font_size: "12sp"
            size_hint_x: .75




MDScreen:
    name: "main"
    MDFloatLayout:
        id: thefloat
        MDLabel:
            text: ""
        theStack:
            id: ss
            ToDoCard

        MDFloatingActionButton:
            icon: "clipboard-list-outline"
            text_color: get_color_from_hex("#231b2d")
            pos_hint: {'center_x': .83, 'center_y': .3}
            md_bg_color: get_color_from_hex("#008080")
            on_press: ss.change()
```
